apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeploymenthpa
  namespace: testns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  strategy:
       type: RollingUpdate
       rollingUpdate:
         maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: vignesh130597/java-web-test-application:5
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvchpa
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpadeploymentautoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: javawebappdeploymenthpa
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  - type: Resource
    resource:
     name: memory
     target:
      type: Utilization
      averageUtilization: 40


